// AUTO-GENERATED - DO NOT EDIT
// This file is generated by the plugin discovery esbuild plugin

export const RESOURCE_LOADERS = {
  devices: async () => {
    const module = await import('../mcp/resources/devices.ts');
    return module.default;
  },
  doctor: async () => {
    const module = await import('../mcp/resources/doctor.ts');
    return module.default;
  },
  'session-status': async () => {
    const module = await import('../mcp/resources/session-status.ts');
    return module.default;
  },
  simulators: async () => {
    const module = await import('../mcp/resources/simulators.ts');
    return module.default;
  },
};

export type ResourceName = keyof typeof RESOURCE_LOADERS;
